### PR TITLE
V3 to master. Do not merge, please.

### PR DESCRIPTION
**Pull request by featalion**
Rebased version of v3 client library.

### CODE REVIEW

**Comment by featalion** [comment]
@sunloverz please, test it. Thanks!

**Comment by sunloverz** [comment]
@featalion everything works fine

**Comment by featalion** [comment]
`featalion:v3`, right? ( : moved current `v3 -> v3-old`, and push current PR's code to `v3`

**Comment by featalion** [comment]
waiting for IronMQ backend v3 to be upstream and then merge.

**Pull request merged**
