### PR TITLE
replace v2 with v3 endpoint and removed rackspace v2 endpoint

### PR DESCRIPTION
**Pull request by Stephenitis**
default host is now 
`mq-aws-us-east-1-1.iron.io`

1. I edited the coffeescript
2. Compiled the coffeescript into javascript `coffee --compile --output lib/ src/`

### CODE REVIEW

**Comment by Stephenitis** [comment]
@featalion  can you check

my coffeescript compilation seems to have changed 

```js
__extends
__hasprop
```

to

```js
extends
hasProp
```

**Comment by Stephenitis** [comment]
@featalion ping

**Comment by ysadka** [comment]
Hey @featalion and @thousandsofthem can we get this merged in the next two days?

**Comment by arschles** [comment]
this LGTM

**Pull request merged**
